database:
  path: "../../data/noshow.db"

features:
  target: "no_show"
  num_map:
    one: "1"
    two: "2"
  standard_list:
    # - "arrival_day"
    # - "checkout_day"
    - "sgd_price"
  one_hot_list:
    - "branch"
    - "booking_month"
    # - "arrival_month" #done one-hot
    - "checkout_month"
    - "num_adults"
    - "num_children"
    - "country"

    - "first_time" #1 / 0
    - "room" #'Single' 'King' 'Queen' 'NA' 'President Suite'
    - "platform" #web,agent,email,phone

model:
  test_size: 0.2
  random_state: 42
  name_list: # Valid values are "Logistic Regression/Random Forest/SVC/MLP/XG Boost
    - "Logistic Regression"
    - "Random Forest"
    - "SVC"
    - "MLP"
    - "Naive Bayes"
    - "XG Boost"
  search_method: "grid" # Valid values are "grid/random"
  cv_num: 5 # Number of cross-validation folds
  scoring: "neg_mean_squared_error"
  num_iter: 50 # Number of iterations for RandomizedSearchCV
  num_jobs: -1 # 0 to n -> Use n number of CPUs, -1 -> Use all available CPUs

logistic:
  solver_list:
    - "lbfgs"
    - "liblinear"
    # - "sag" # Cannot converge for lower max_iter value
    - "newton-cg"
    - "newton-cholesky"
  max_iter_list:
    - 100
    - 125
    - 150
    - 175
    - 200
  c_list:
    - 0.1
    - 1
    - 5
    - 10
    - 15
    - 20
  class_weight_list:
    - "balanced"
    - { 0: 1, 1: 1.7 }
    - { 0: 1, 1: 2 }
    - { 0: 1, 1: 5 }

rand_forest:
  est_list: #
    - 100
    - 125
    - 150
    - 175
    - 200
    - 225
    - 250
    - 275
    - 300
    - 325
    - 350
    - 375
    - 400
  depth_list:
    - 5
    - 10
    - 15
    - 20
    - 25
    - 30
    - 35
    - 40
  class_weight_list:
    - "balanced"
    - { 0: 1, 1: 1.7 }
    - { 0: 1, 1: 2 }
    - { 0: 1, 1: 5 }

svc:
  c_list:
    - 0.1
    - 1
    - 5
    - 10
    - 15
    - 20
  kernel_list:
    - "linear"
    - "rbf" # Radial basis function - Effective for non-linear
    - "sigmoid" # Similar to neural network
  class_weight_list:
    - "balanced"
    - { 0: 1, 1: 1.7 }
    - { 0: 1, 1: 2 }
    - { 0: 1, 1: 5 }

mlp:
  hidden_layer_sizes_list:
    - [50, 50]
    - [100, 50]
    - [100, 100]
  activation_list:
    - "relu" #
    - "tanh" #
  solver_list:
    - "adam"
    - "sgd"
  learning_rate_list:
    - "constant"
    - "adaptive"
  max_iter_list:
    - 500
    - 1000
    - 1500
    - 2000

bayes:
  alpha_list:
    - 0.01
    - 0.1
    - 1.0
    - 1.5
    - 2.0
    - 3.0

xgb:
  learning_rate_list:
    - 0.01
    - 0.05
    - 0.1
  max_depth_list:
    - 3
    - 5
    - 7
    - 10
  subsample_list:
    - 0.6
    - 0.8
    - 1.0
